=== Awelless/fourth-task/src/test/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        elementFormDefault="qualified">

    <element name="tariff" type="tns:Tariff" />
    <element name="tariffWithMonthlyFee" type="tns:TariffWithMonthlyFee" substitutionGroup="tns:tariff" />

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Tariff">
        <sequence>
            <element name="operatorName" type="string" />
            <element name="prices" type="tns:Prices"/>
            <element name="connectionFee" type="nonNegativeInteger" />
            <element name="tariffication">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="15 seconds" />
                        <enumeration value="minute" />
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="name" type="string" use="required" />
    </complexType>

    <complexType name="TariffWithMonthlyFee">
        <complexContent>
            <extension base="tns:Tariff">
                <attribute name="monthlyFee" type="nonNegativeInteger" use="required" />
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Prices">
        <sequence>
            <element name="callToThisOperator" type="nonNegativeInteger" />
            <element name="callToOtherOperators" type="nonNegativeInteger" />
            <element name="callToStationary" type="nonNegativeInteger" />
            <element name="sms" type="nonNegativeInteger" />
        </sequence>
    </complexType>

</schema>

=== Awelless/fourth-task/src/test/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tariffs xmlns="http://www.example.com/tariffs"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">

    <tariff name="NoMonthlyFee">
        <operatorName>T-Mobile</operatorName>
        <prices>
            <callToThisOperator>12</callToThisOperator>
            <callToOtherOperators>22</callToOtherOperators>
            <callToStationary>30</callToStationary>
            <sms>12</sms>
        </prices>
        <connectionFee>20</connectionFee>
        <tariffication>15 seconds</tariffication>
    </tariff>

    <tariffWithMonthlyFee name="WithFee" monthlyFee="50">
        <operatorName>T-Mobile</operatorName>
        <prices>
            <callToThisOperator>10</callToThisOperator>
            <callToOtherOperators>20</callToOtherOperators>
            <callToStationary>25</callToStationary>
            <sms>11</sms>
        </prices>
        <connectionFee>35</connectionFee>
        <tariffication>minute</tariffication>
    </tariffWithMonthlyFee>

</tariffs>
